import type { Metadata } from "next";
import "./globals.css";
import Footer from "../components/footer";
import Navbar from "../components/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased font-Epilogue font-semibold text-txt-2 min-h-screen flex flex-col max-w-360 m-auto`}>

        <Navbar></Navbar>

        <div className="grow">
          {children}
        </div>

        <Footer></Footer>

      </body>
    </html>
  );
}
